/**
 * DL_Master curriculum reference library.
 * Real URLs from renowned courses, papers, books, and documentation.
 */

const CATALOG = {
  // ── Python fundamentals ──────────────────────────────────────────────
  'python-tutorial-intro': {
    id: 'python-tutorial-intro',
    title: 'Python Tutorial — An Informal Introduction',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/introduction.html',
    description: 'Official introduction to Python variables, numbers, and strings.',
  },
  'python-datamodel': {
    id: 'python-datamodel',
    title: 'Python Data Model',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/reference/datamodel.html',
    description: 'Deep dive into objects, types, and the semantics behind Python values.',
  },
  'real-python-variables': {
    id: 'real-python-variables',
    title: 'Variables in Python',
    source: 'Real Python',
    type: 'documentation',
    url: 'https://realpython.com/python-variables/',
    description: 'Practical guide to naming, assignment, and dynamic typing in Python.',
  },
  'cs106a-python': {
    id: 'cs106a-python',
    title: 'Stanford CS106A — Programming Methodology',
    source: 'Stanford',
    type: 'course',
    url: 'https://cs106a.stanford.edu/',
    description: 'Foundational Stanford course covering Python programming from first principles.',
  },
  'python-operators-doc': {
    id: 'python-operators-doc',
    title: 'Python Operator Reference',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/operator.html',
    description: 'Complete reference for arithmetic, comparison, and logical operators.',
  },
  'real-python-operators': {
    id: 'real-python-operators',
    title: 'Operators and Expressions in Python',
    source: 'Real Python',
    type: 'documentation',
    url: 'https://realpython.com/python-operators-expressions/',
    description: 'Explains operator precedence, short-circuit evaluation, and common pitfalls.',
  },
  'python-strings-doc': {
    id: 'python-strings-doc',
    title: 'Python Text Sequence Type — str',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/stdtypes.html#text-sequence-type-str',
    description: 'Official documentation for string methods, slicing, and immutability.',
  },
  'real-python-strings': {
    id: 'real-python-strings',
    title: 'Python Strings and Character Data',
    source: 'Real Python',
    type: 'documentation',
    url: 'https://realpython.com/python-strings/',
    description: 'Hands-on coverage of formatting, encoding, and text processing patterns.',
  },
  'python-fstrings-pep498': {
    id: 'python-fstrings-pep498',
    title: 'PEP 498 — Literal String Interpolation',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://peps.python.org/pep-0498/',
    description: 'Specification for f-strings, the preferred modern formatting approach.',
  },
  'python-input-output': {
    id: 'python-input-output',
    title: 'Input and Output',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/inputoutput.html',
    description: 'Covers print formatting, reading input, and file I/O fundamentals.',
  },
  'python-repl': {
    id: 'python-repl',
    title: 'Interactive Python Shell',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/interpreter.html',
    description: 'How to use the REPL for rapid experimentation and debugging.',
  },
  'python-venv-doc': {
    id: 'python-venv-doc',
    title: 'venv — Creation of Virtual Environments',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/venv.html',
    description: 'Standard library tool for isolating project dependencies.',
  },
  'pip-user-guide': {
    id: 'pip-user-guide',
    title: 'pip User Guide',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://pip.pypa.io/en/stable/user_guide/',
    description: 'Installing, upgrading, and managing Python packages with pip.',
  },
  'python-packaging-guide': {
    id: 'python-packaging-guide',
    title: 'Python Packaging User Guide',
    source: 'PyPA',
    type: 'documentation',
    url: 'https://packaging.python.org/en/latest/tutorials/installing-packages/',
    description: 'Best practices for project setup, virtual environments, and distribution.',
  },
  // ── Control flow & functions ─────────────────────────────────────────
  'python-if-doc': {
    id: 'python-if-doc',
    title: 'More Control Flow Tools — if Statements',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/controlflow.html#if-statements',
    description: 'Official tutorial on conditionals, elif chains, and boolean logic.',
  },
  'python-loops-doc': {
    id: 'python-loops-doc',
    title: 'for and while Loops',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/controlflow.html#for-statements',
    description: 'Iteration over sequences, range(), and loop control with break/continue.',
  },
  'python-functions-doc': {
    id: 'python-functions-doc',
    title: 'Defining Functions',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/controlflow.html#defining-functions',
    description: 'Function definition, parameters, return values, and docstrings.',
  },
  'real-python-scope': {
    id: 'real-python-scope',
    title: 'Namespaces and Scope in Python',
    source: 'Real Python',
    type: 'documentation',
    url: 'https://realpython.com/python-namespaces-scope/',
    description: 'LEGB rule, closures, and how Python resolves variable names.',
  },
  'python-lambda-doc': {
    id: 'python-lambda-doc',
    title: 'Lambda Expressions',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/controlflow.html#lambda-expressions',
    description: 'Anonymous functions for concise one-expression callbacks.',
  },
  'python-comprehensions-doc': {
    id: 'python-comprehensions-doc',
    title: 'List Comprehensions',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/datastructures.html#list-comprehensions',
    description: 'Concise syntax for building lists, dicts, and sets from iterables.',
  },
  'python-iterators-doc': {
    id: 'python-iterators-doc',
    title: 'Iterator Protocol',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/stdtypes.html#iterator-types',
    description: 'How __iter__ and __next__ enable lazy, memory-efficient iteration.',
  },
  // ── Data structures ──────────────────────────────────────────────────
  'python-lists-doc': {
    id: 'python-lists-doc',
    title: 'More on Lists',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/datastructures.html#more-on-lists',
    description: 'List methods, slicing, stacking, and queue operations.',
  },
  'python-dicts-doc': {
    id: 'python-dicts-doc',
    title: 'Dictionaries',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/datastructures.html#dictionaries',
    description: 'Hash maps with key-value pairs, views, and comprehension syntax.',
  },
  'python-sets-doc': {
    id: 'python-sets-doc',
    title: 'Sets',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/datastructures.html#sets',
    description: 'Unordered collections for membership testing and set algebra.',
  },
  'python-deque-doc': {
    id: 'python-deque-doc',
    title: 'collections.deque',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/collections.html#collections.deque',
    description: 'Double-ended queue optimized for O(1) append/pop at both ends.',
  },
  'python-sort-doc': {
    id: 'python-sort-doc',
    title: 'Sorting HOW TO',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/howto/sorting.html',
    description: 'Guide to sorted(), list.sort(), key functions, and stability.',
  },
  'python-bisect-doc': {
    id: 'python-bisect-doc',
    title: 'bisect — Array Bisection Algorithm',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/bisect.html',
    description: 'Binary search utilities for maintaining sorted sequences.',
  },
  'python-collections-module': {
    id: 'python-collections-module',
    title: 'collections Module',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/collections.html',
    description: 'Specialized containers: namedtuple, Counter, defaultdict, ChainMap.',
  },
  'clrs-algorithms': {
    id: 'clrs-algorithms',
    title: 'Introduction to Algorithms (CLRS)',
    source: 'MIT Press',
    type: 'book',
    url: 'https://mitpress.mit.edu/9780262046305/introduction-to-algorithms/',
    description: 'Definitive reference for sorting, searching, and algorithmic complexity analysis.',
  },
  // ── OOP & advanced Python ──────────────────────────────────────────
  'python-classes-doc': {
    id: 'python-classes-doc',
    title: 'Classes',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/classes.html',
    description: 'Class definition, instances, methods, and inheritance fundamentals.',
  },
  'python-inheritance-doc': {
    id: 'python-inheritance-doc',
    title: 'Inheritance',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/classes.html#inheritance',
    description: 'Base classes, method overriding, isinstance(), and multiple inheritance.',
  },
  'python-properties-doc': {
    id: 'python-properties-doc',
    title: 'property — Attribute Access',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/functions.html#property',
    description: 'Managed attributes with getters, setters, and encapsulation patterns.',
  },
  'python-design-patterns': {
    id: 'python-design-patterns',
    title: 'Python Design Patterns Guide',
    source: 'Refactoring Guru',
    type: 'documentation',
    url: 'https://refactoring.guru/design-patterns/python',
    description: 'Catalog of creational, structural, and behavioral patterns in Python.',
  },
  'python-abc-doc': {
    id: 'python-abc-doc',
    title: 'abc — Abstract Base Classes',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/abc.html',
    description: 'Define interfaces and enforce method implementation in subclasses.',
  },
  'python-typing-protocol': {
    id: 'python-typing-protocol',
    title: 'typing.Protocol — Structural Subtyping',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/typing.html#typing.Protocol',
    description: 'Duck-typing interfaces without explicit inheritance.',
  },
  'python-decorators-doc': {
    id: 'python-decorators-doc',
    title: 'Primer on Python Decorators',
    source: 'Real Python',
    type: 'documentation',
    url: 'https://realpython.com/primer-on-python-decorators/',
    description: 'Functions wrapping functions — essential for frameworks and cross-cutting concerns.',
  },
  'python-generators-doc': {
    id: 'python-generators-doc',
    title: 'Generator Expressions & yield',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/howto/functional.html#generators',
    description: 'Lazy iteration with generator functions and memory-efficient pipelines.',
  },
  'python-context-managers': {
    id: 'python-context-managers-doc',
    title: 'Context Managers',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/reference/datamodel.html#context-managers',
    description: 'Resource management with __enter__/__exit__ and the with statement.',
  },
  'python-contextlib-doc': {
    id: 'python-contextlib-doc',
    title: 'contextlib Utilities',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/contextlib.html',
    description: 'Helpers like @contextmanager for writing context managers easily.',
  },
  'python-type-hints-doc': {
    id: 'python-type-hints-doc',
    title: 'Typing — Support for Type Hints',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/typing.html',
    description: 'Static type annotations for safer, more maintainable Python code.',
  },
  'python-dataclasses-doc': {
    id: 'python-dataclasses-doc',
    title: 'dataclasses Module',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/library/dataclasses.html',
    description: 'Boilerplate-free classes for storing data with auto-generated methods.',
  },
  'python-modules-doc': {
    id: 'python-modules-doc',
    title: 'Modules and Packages',
    source: 'Python.org',
    type: 'documentation',
    url: 'https://docs.python.org/3/tutorial/modules.html',
    description: 'Organizing code into importable modules and package hierarchies.',
  },
  // ── NumPy & Pandas ───────────────────────────────────────────────────
  'numpy-quickstart': {
    id: 'numpy-quickstart',
    title: 'NumPy Quickstart Tutorial',
    source: 'NumPy',
    type: 'documentation',
    url: 'https://numpy.org/doc/stable/user/quickstart.html',
    description: 'Creating arrays, indexing, and basic operations with ndarrays.',
  },
  'numpy-ndarray': {
    id: 'numpy-ndarray',
    title: 'The N-dimensional Array (ndarray)',
    source: 'NumPy',
    type: 'documentation',
    url: 'https://numpy.org/doc/stable/reference/arrays.ndarray.html',
    description: 'Core ndarray structure — shape, dtype, strides, and memory layout.',
  },
  'numpy-indexing': {
    id: 'numpy-indexing',
    title: 'Indexing and Slicing Arrays',
    source: 'NumPy',
    type: 'documentation',
    url: 'https://numpy.org/doc/stable/user/basics.indexing.html',
    description: 'Basic, advanced, and boolean indexing for multidimensional arrays.',
  },
  'numpy-broadcasting': {
    id: 'numpy-broadcasting',
    title: 'Array Broadcasting in NumPy',
    source: 'NumPy',
    type: 'documentation',
    url: 'https://numpy.org/doc/stable/user/basics.broadcasting.html',
    description: 'Rules for operating on arrays of different shapes without copying.',
  },
  'numpy-linalg': {
    id: 'numpy-linalg',
    title: 'numpy.linalg — Linear Algebra',
    source: 'NumPy',
    type: 'documentation',
    url: 'https://numpy.org/doc/stable/reference/routines.linalg.html',
    description: 'Matrix multiplication, decomposition, eigenvalues, and linear systems.',
  },
  'numpy-random': {
    id: 'numpy-random',
    title: 'Random Sampling (numpy.random)',
    source: 'NumPy',
    type: 'documentation',
    url: 'https://numpy.org/doc/stable/reference/random/index.html',
    description: 'Reproducible random number generation and statistical distributions.',
  },
  'numpy-performance': {
    id: 'numpy-performance',
    title: 'Performance Tips for NumPy',
    source: 'NumPy',
    type: 'documentation',
    url: 'https://numpy.org/doc/stable/user/performance.html',
    description: 'Vectorization strategies to avoid slow Python loops over arrays.',
  },
  'pandas-getting-started': {
    id: 'pandas-getting-started',
    title: 'Getting Started with pandas',
    source: 'Pandas',
    type: 'documentation',
    url: 'https://pandas.pydata.org/docs/getting_started/index.html',
    description: 'Introductory guide to Series, DataFrames, and basic operations.',
  },
  'pandas-indexing': {
    id: 'pandas-indexing',
    title: 'Indexing and Selecting Data',
    source: 'Pandas',
    type: 'documentation',
    url: 'https://pandas.pydata.org/docs/user_guide/indexing.html',
    description: 'loc, iloc, boolean masks, query(), and multi-index selection.',
  },
  'pandas-groupby': {
    id: 'pandas-groupby',
    title: 'Group By: Split-Apply-Combine',
    source: 'Pandas',
    type: 'documentation',
    url: 'https://pandas.pydata.org/docs/user_guide/groupby.html',
    description: 'Grouped aggregations, transformations, and filtering patterns.',
  },
  'pandas-merge': {
    id: 'pandas-merge',
    title: 'Merge, Join, Concatenate and Compare',
    source: 'Pandas',
    type: 'documentation',
    url: 'https://pandas.pydata.org/docs/user_guide/merging.html',
    description: 'Combining DataFrames with SQL-like join operations.',
  },
  'pandas-missing': {
    id: 'pandas-missing',
    title: 'Working with Missing Data',
    source: 'Pandas',
    type: 'documentation',
    url: 'https://pandas.pydata.org/docs/user_guide/missing_data.html',
    description: 'Detecting, filling, and dropping NaN values in tabular data.',
  },
  'pandas-timeseries': {
    id: 'pandas-timeseries',
    title: 'Time Series / Date Functionality',
    source: 'Pandas',
    type: 'documentation',
    url: 'https://pandas.pydata.org/docs/user_guide/timeseries.html',
    description: 'DatetimeIndex, resampling, and time-based aggregations.',
  },
  'kaggle-python': {
    id: 'kaggle-python',
    title: 'Kaggle Learn — Python',
    source: 'Kaggle',
    type: 'course',
    url: 'https://www.kaggle.com/learn/python',
    description: 'Interactive micro-course covering Python essentials for data science.',
  },
  'kaggle-pandas': {
    id: 'kaggle-pandas',
    title: 'Kaggle Learn — Pandas',
    source: 'Kaggle',
    type: 'course',
    url: 'https://www.kaggle.com/learn/pandas',
    description: 'Hands-on pandas exercises for real-world data manipulation.',
  },
  // ── Visualization ────────────────────────────────────────────────────
  'matplotlib-pyplot': {
    id: 'matplotlib-pyplot',
    title: 'Matplotlib Pyplot Tutorial',
    source: 'Matplotlib',
    type: 'documentation',
    url: 'https://matplotlib.org/stable/tutorials/pyplot.html',
    description: 'Creating line, scatter, bar, and histogram plots with pyplot.',
  },
  'matplotlib-oo': {
    id: 'matplotlib-oo',
    title: 'Matplotlib Object-Oriented Interface',
    source: 'Matplotlib',
    type: 'documentation',
    url: 'https://matplotlib.org/stable/users/explain/figure/api_interfaces.html',
    description: 'Figure and Axes API for fine-grained control over visualizations.',
  },
  'seaborn-tutorial': {
    id: 'seaborn-tutorial',
    title: 'Seaborn Tutorial',
    source: 'Seaborn',
    type: 'documentation',
    url: 'https://seaborn.pydata.org/tutorial.html',
    description: 'Statistical visualizations built on matplotlib with elegant defaults.',
  },
  'plotly-python': {
    id: 'plotly-python',
    title: 'Plotly Python Graphing Library',
    source: 'Plotly',
    type: 'documentation',
    url: 'https://plotly.com/python/',
    description: 'Interactive charts for exploration, dashboards, and web deployment.',
  },
  'tufte-visual-display': {
    id: 'tufte-visual-display',
    title: 'The Visual Display of Quantitative Information',
    source: 'Edward Tufte',
    type: 'book',
    url: 'https://www.edwardtufte.com/books/vdqi/',
    description: 'Classic principles of honest, effective data visualization design.',
  },
  'kaggle-data-viz': {
    id: 'kaggle-data-viz',
    title: 'Kaggle Learn — Data Visualization',
    source: 'Kaggle',
    type: 'course',
    url: 'https://www.kaggle.com/learn/data-visualization',
    description: 'Practical chart selection and storytelling with seaborn.',
  },
  // ── ML Math & Foundations ────────────────────────────────────────────
  '3blue1brown-linalg': {
    id: '3blue1brown-linalg',
    title: 'Essence of Linear Algebra',
    source: '3Blue1Brown',
    type: 'video',
    url: 'https://www.3blue1brown.com/topics/linear-algebra',
    description: 'Visual intuition for vectors, matrices, and transformations.',
  },
  'mit-1806-linalg': {
    id: 'mit-1806-linalg',
    title: 'MIT 18.06 Linear Algebra',
    source: 'MIT',
    type: 'course',
    url: 'https://ocw.mit.edu/courses/18-06-linear-algebra-spring-2010/',
    description: 'Gilbert Strang\'s foundational linear algebra course used across ML.',
  },
  '3blue1brown-calculus': {
    id: '3blue1brown-calculus',
    title: 'Essence of Calculus',
    source: '3Blue1Brown',
    type: 'video',
    url: 'https://www.3blue1brown.com/topics/calculus',
    description: 'Geometric intuition for derivatives, integrals, and the chain rule.',
  },
  'khan-multivariable-calc': {
    id: 'khan-multivariable-calc',
    title: 'Multivariable Calculus — Khan Academy',
    source: 'Khan Academy',
    type: 'course',
    url: 'https://www.khanacademy.org/math/multivariable-calculus',
    description: 'Partial derivatives and gradients essential for neural network training.',
  },
  'khan-probability': {
    id: 'khan-probability',
    title: 'Statistics and Probability — Khan Academy',
    source: 'Khan Academy',
    type: 'course',
    url: 'https://www.khanacademy.org/math/statistics-probability',
    description: 'Probability distributions, Bayes theorem, and statistical inference.',
  },
  'bishop-prml': {
    id: 'bishop-prml',
    title: 'Pattern Recognition and Machine Learning',
    source: 'Cambridge',
    type: 'book',
    url: 'https://www.microsoft.com/en-us/research/publication/pattern-recognition-machine-learning/',
    description: 'Rigorous treatment of probability, inference, and classical ML algorithms.',
  },
  'cover-thomas-info-theory': {
    id: 'cover-thomas-info-theory',
    title: 'Elements of Information Theory',
    source: 'Wiley',
    type: 'book',
    url: 'https://www.elementsofinformationtheory.com/',
    description: 'Definitive reference for entropy, mutual information, and coding theory.',
  },
  'cs229-optimization': {
    id: 'cs229-optimization',
    title: 'CS229 Lecture Notes — Optimization',
    source: 'Stanford CS229',
    type: 'course',
    url: 'https://cs229.stanford.edu/notes2022fall/main_notes.pdf',
    description: 'Gradient descent, Newton\'s method, and convergence analysis for ML.',
  },
  'adam-paper': {
    id: 'adam-paper',
    title: 'Adam: A Method for Stochastic Optimization',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1412.6980',
    description: 'Adaptive learning rate optimizer used as default in most deep learning training.',
  },
  // ── ML Courses & Books ───────────────────────────────────────────────
  'stanford-cs229': {
    id: 'stanford-cs229',
    title: 'Stanford CS229 — Machine Learning',
    source: 'Stanford CS229',
    type: 'course',
    url: 'https://cs229.stanford.edu/',
    description: 'Andrew Ng\'s graduate ML course — the canonical theoretical foundation.',
  },
  'mit-6036': {
    id: 'mit-6036',
    title: 'MIT 6.036 — Introduction to Machine Learning',
    source: 'MIT',
    type: 'course',
    url: 'https://introml.mit.edu/',
    description: 'MIT\'s hands-on intro covering models, loss, and generalization.',
  },
  'berkeley-cs189': {
    id: 'berkeley-cs189',
    title: 'Berkeley CS189/289A — Introduction to Machine Learning',
    source: 'Berkeley',
    type: 'course',
    url: 'https://people.eecs.berkeley.edu/~jrs/189/',
    description: 'Comprehensive ML course with strong mathematical foundations.',
  },
  'cmu-10701': {
    id: 'cmu-10701',
    title: 'CMU 10-701 — Introduction to Machine Learning',
    source: 'CMU',
    type: 'course',
    url: 'https://www.cs.cmu.edu/~10701/',
    description: 'Carnegie Mellon graduate introduction to probabilistic ML methods.',
  },
  'oxford-ml': {
    id: 'oxford-ml',
    title: 'Oxford Machine Learning',
    source: 'Oxford',
    type: 'course',
    url: 'https://www.cs.ox.ac.uk/teaching/courses/ml/',
    description: 'Oxford\'s ML course covering probabilistic modeling and inference.',
  },
  'esl-hastie': {
    id: 'esl-hastie',
    title: 'The Elements of Statistical Learning',
    source: 'Stanford',
    type: 'book',
    url: 'https://hastie.su.domains/ElemStatLearn/',
    description: 'Free authoritative text on statistical learning methods and theory.',
  },
  'coursera-andrew-ng': {
    id: 'coursera-andrew-ng',
    title: 'Machine Learning Specialization',
    source: 'Coursera',
    type: 'course',
    url: 'https://www.coursera.org/specializations/machine-learning-introduction',
    description: 'Andrew Ng\'s accessible introduction to supervised and unsupervised learning.',
  },
  'scikit-learn-user-guide': {
    id: 'scikit-learn-user-guide',
    title: 'scikit-learn User Guide',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/user_guide.html',
    description: 'Complete reference for ML algorithms, pipelines, and model selection.',
  },
  'kaggle-intro-ml': {
    id: 'kaggle-intro-ml',
    title: 'Kaggle Learn — Intro to Machine Learning',
    source: 'Kaggle',
    type: 'course',
    url: 'https://www.kaggle.com/learn/intro-to-machine-learning',
    description: 'Practical first steps with decision trees and model validation.',
  },
  'kaggle-intermediate-ml': {
    id: 'kaggle-intermediate-ml',
    title: 'Kaggle Learn — Intermediate Machine Learning',
    source: 'Kaggle',
    type: 'course',
    url: 'https://www.kaggle.com/learn/intermediate-machine-learning',
    description: 'Missing values, categorical variables, and pipeline best practices.',
  },
  // ── Supervised & Unsupervised ML ─────────────────────────────────────
  'sklearn-linear-models': {
    id: 'sklearn-linear-models',
    title: 'scikit-learn Linear Models',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/linear_model.html',
    description: 'Linear, logistic, ridge, lasso, and elastic net regression implementations.',
  },
  'sklearn-trees': {
    id: 'sklearn-trees',
    title: 'scikit-learn Decision Trees',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/tree.html',
    description: 'Decision trees, random forests, and ensemble tree methods.',
  },
  'sklearn-metrics': {
    id: 'sklearn-metrics',
    title: 'scikit-learn Model Evaluation',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/model_evaluation.html',
    description: 'Accuracy, precision, recall, F1, ROC-AUC, and regression metrics.',
  },
  'sklearn-cross-validation': {
    id: 'sklearn-cross-validation',
    title: 'scikit-learn Cross-Validation',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/cross_validation.html',
    description: 'K-fold, stratified, and nested cross-validation for robust evaluation.',
  },
  'sklearn-pipeline': {
    id: 'sklearn-pipeline',
    title: 'scikit-learn Pipelines',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/compose.html',
    description: 'Chaining transformers and estimators into reproducible workflows.',
  },
  'sklearn-svm': {
    id: 'sklearn-svm',
    title: 'scikit-learn Support Vector Machines',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/svm.html',
    description: 'SVC, SVR, and kernel methods for maximum-margin classification.',
  },
  'xgboost-docs': {
    id: 'xgboost-docs',
    title: 'XGBoost Documentation',
    source: 'XGBoost',
    type: 'documentation',
    url: 'https://xgboost.readthedocs.io/en/stable/',
    description: 'Industry-standard gradient boosting library for tabular data.',
  },
  'lightgbm-docs': {
    id: 'lightgbm-docs',
    title: 'LightGBM Documentation',
    source: 'Microsoft',
    type: 'documentation',
    url: 'https://lightgbm.readthedocs.io/en/latest/',
    description: 'Fast gradient boosting with leaf-wise tree growth for large datasets.',
  },
  'sklearn-ensemble': {
    id: 'sklearn-ensemble',
    title: 'scikit-learn Ensemble Methods',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/ensemble.html',
    description: 'Bagging, boosting, stacking, and voting classifiers.',
  },
  'sklearn-clustering': {
    id: 'sklearn-clustering',
    title: 'scikit-learn Clustering',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/clustering.html',
    description: 'K-Means, DBSCAN, hierarchical, and spectral clustering algorithms.',
  },
  'sklearn-pca': {
    id: 'sklearn-pca',
    title: 'scikit-learn PCA & Decomposition',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/decomposition.html',
    description: 'PCA, NMF, and other dimensionality reduction techniques.',
  },
  'van-der-maaten-tsne': {
    id: 'van-der-maaten-tsne',
    title: 'Visualizing Data using t-SNE',
    source: 'JMLR',
    type: 'paper',
    url: 'https://www.jmlr.org/papers/volume9/vandermaaten08a/vandermaaten08a.pdf',
    description: 'Seminal paper on t-SNE for nonlinear dimensionality reduction visualization.',
  },
  'sklearn-anomaly': {
    id: 'sklearn-anomaly',
    title: 'scikit-learn Outlier Detection',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/outlier_detection.html',
    description: 'Isolation Forest, Local Outlier Factor, and novelty detection methods.',
  },
  'sklearn-association': {
    id: 'sklearn-association',
    title: 'mlxtend — Association Rules',
    source: 'mlxtend',
    type: 'documentation',
    url: 'https://rasbt.github.io/mlxtend/user_guide/frequent_patterns/apriori/',
    description: 'Apriori algorithm for frequent itemset and association rule mining.',
  },
  'sklearn-mixture': {
    id: 'sklearn-mixture',
    title: 'scikit-learn Gaussian Mixture Models',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/mixture.html',
    description: 'Probabilistic clustering with soft assignments via EM algorithm.',
  },
  'sklearn-preprocessing': {
    id: 'sklearn-preprocessing',
    title: 'scikit-learn Preprocessing',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/preprocessing.html',
    description: 'Scaling, encoding, imputation, and feature transformation utilities.',
  },
  'sklearn-feature-selection': {
    id: 'sklearn-feature-selection',
    title: 'scikit-learn Feature Selection',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/feature_selection.html',
    description: 'Filter, wrapper, and embedded methods for selecting informative features.',
  },
  'sklearn-grid-search': {
    id: 'sklearn-grid-search',
    title: 'scikit-learn Hyperparameter Tuning',
    source: 'scikit-learn',
    type: 'documentation',
    url: 'https://scikit-learn.org/stable/modules/grid_search.html',
    description: 'GridSearchCV and RandomizedSearchCV for systematic hyperparameter optimization.',
  },
  'ml-bias-variance-tradeoff': {
    id: 'ml-bias-variance-tradeoff',
    title: 'Understanding the Bias-Variance Tradeoff',
    source: 'mlu.explain',
    type: 'documentation',
    url: 'https://mlu-explain.github.io/bias-variance/',
    description: 'Interactive explanation of underfitting, overfitting, and model complexity.',
  },
  'shap-docs': {
    id: 'shap-docs',
    title: 'SHAP Documentation',
    source: 'SHAP',
    type: 'documentation',
    url: 'https://shap.readthedocs.io/en/latest/',
    description: 'Unified framework for explaining model predictions with Shapley values.',
  },
  'lime-paper': {
    id: 'lime-paper',
    title: '"Why Should I Trust You?" — Explaining Predictions (LIME)',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1602.04938',
    description: 'Local interpretable model-agnostic explanations for any classifier.',
  },
  // ── Deep Learning Fundamentals ───────────────────────────────────────
  'goodfellow-dl-book': {
    id: 'goodfellow-dl-book',
    title: 'Deep Learning',
    source: 'MIT Press',
    type: 'book',
    url: 'https://www.deeplearningbook.org/',
    description: 'Comprehensive free textbook covering neural networks, optimization, and architectures.',
  },
  'stanford-cs230': {
    id: 'stanford-cs230',
    title: 'Stanford CS230 — Deep Learning',
    source: 'Stanford CS230',
    type: 'course',
    url: 'http://cs230.stanford.edu/',
    description: 'Andrew Ng\'s deep learning course covering NN fundamentals and best practices.',
  },
  'mit-6s191': {
    id: 'mit-6s191',
    title: 'MIT 6.S191 — Introduction to Deep Learning',
    source: 'MIT',
    type: 'course',
    url: 'http://introtodeeplearning.com/',
    description: 'Accessible MIT course with lectures on CNNs, RNNs, and generative models.',
  },
  'fastai-course': {
    id: 'fastai-course',
    title: 'fast.ai Practical Deep Learning',
    source: 'fast.ai',
    type: 'course',
    url: 'https://course.fast.ai/',
    description: 'Top-down, code-first approach to training state-of-the-art models.',
  },
  'cmu-11785': {
    id: 'cmu-11785',
    title: 'CMU 11-785 — Introduction to Deep Learning',
    source: 'CMU',
    type: 'course',
    url: 'https://deeplearning.cs.cmu.edu/',
    description: 'Rigorous deep learning course from Bhiksha Raj covering theory and practice.',
  },
  'oxford-dl': {
    id: 'oxford-dl',
    title: 'Oxford Deep Learning',
    source: 'Oxford',
    type: 'course',
    url: 'https://www.cs.ox.ac.uk/people/nando.de_freitas/learningdeep/',
    description: 'Nando de Freitas\' deep learning course with video lectures and notes.',
  },
  '3blue1brown-nn': {
    id: '3blue1brown-nn',
    title: 'Neural Networks — 3Blue1Brown',
    source: '3Blue1Brown',
    type: 'video',
    url: 'https://www.3blue1brown.com/topics/neural-networks',
    description: 'Visual intuition for neurons, layers, backpropagation, and gradient descent.',
  },
  'dropout-paper': {
    id: 'dropout-paper',
    title: 'Dropout: A Simple Way to Prevent Neural Networks from Overfitting',
    source: 'JMLR',
    type: 'paper',
    url: 'https://jmlr.org/papers/v15/srivastava14a.html',
    description: 'Foundational regularization technique randomly dropping units during training.',
  },
  'batch-norm-paper': {
    id: 'batch-norm-paper',
    title: 'Batch Normalization: Accelerating Deep Network Training',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1502.03167',
    description: 'Normalizes layer inputs to stabilize and accelerate deep network training.',
  },
  // ── PyTorch ──────────────────────────────────────────────────────────
  'pytorch-tutorials': {
    id: 'pytorch-tutorials',
    title: 'PyTorch Tutorials',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/tutorials/',
    description: 'Official tutorials from tensors through training loops and deployment.',
  },
  'pytorch-tensors': {
    id: 'pytorch-tensors',
    title: 'PyTorch Tensor Tutorial',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/tutorials/beginner/basics/tensorqs_tutorial.html',
    description: 'Creating, indexing, and operating on PyTorch tensors with GPU support.',
  },
  'pytorch-autograd': {
    id: 'pytorch-autograd',
    title: 'PyTorch Autograd Mechanics',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/tutorials/beginner/blitz/autograd_tutorial.html',
    description: 'Automatic differentiation and computational graph construction.',
  },
  'pytorch-nn-module': {
    id: 'pytorch-nn-module',
    title: 'PyTorch nn.Module Guide',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/tutorials/beginner/basics/buildmodel_tutorial.html',
    description: 'Object-oriented model definition with layers, parameters, and forward pass.',
  },
  'pytorch-dataloader': {
    id: 'pytorch-dataloader',
    title: 'PyTorch Data Loading Tutorial',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/tutorials/beginner/basics/data_tutorial.html',
    description: 'Dataset, DataLoader, and efficient batching for training pipelines.',
  },
  'pytorch-amp': {
    id: 'pytorch-amp',
    title: 'Automatic Mixed Precision',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/docs/stable/amp.html',
    description: 'Mixed precision training for faster GPU computation with minimal accuracy loss.',
  },
  'pytorch-cuda': {
    id: 'pytorch-cuda',
    title: 'PyTorch CUDA Semantics',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/docs/stable/notes/cuda.html',
    description: 'Moving tensors to GPU, multi-GPU training, and CUDA best practices.',
  },
  // ── CNNs & Computer Vision ───────────────────────────────────────────
  'stanford-cs231n': {
    id: 'stanford-cs231n',
    title: 'Stanford CS231n — CNNs for Visual Recognition',
    source: 'Stanford CS231n',
    type: 'course',
    url: 'http://cs231n.stanford.edu/',
    description: 'Definitive course on convolutional networks and computer vision.',
  },
  'cs231n-conv-notes': {
    id: 'cs231n-conv-notes',
    title: 'CS231n Convolutional Neural Networks',
    source: 'Stanford CS231n',
    type: 'course',
    url: 'https://cs231n.github.io/convolutional-networks/',
    description: 'Detailed notes on convolution, pooling, and spatial feature extraction.',
  },
  'alexnet-paper': {
    id: 'alexnet-paper',
    title: 'ImageNet Classification with Deep Convolutional Neural Networks (AlexNet)',
    source: 'NeurIPS',
    type: 'paper',
    url: 'https://papers.nips.cc/paper/4824-imagenet-classification-with-deep-convolutional-neural-networks',
    description: 'Breakthrough 2012 paper that launched the deep learning revolution in vision.',
  },
  'resnet-paper': {
    id: 'resnet-paper',
    title: 'Deep Residual Learning for Image Recognition (ResNet)',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1512.03385',
    description: 'Skip connections enabling training of very deep networks — foundational architecture.',
  },
  'vgg-paper': {
    id: 'vgg-paper',
    title: 'Very Deep Convolutional Networks (VGG)',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1409.1556',
    description: 'Showed depth with small 3×3 filters improves representation learning.',
  },
  'pytorch-transfer-learning': {
    id: 'pytorch-transfer-learning',
    title: 'PyTorch Transfer Learning Tutorial',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/tutorials/beginner/transfer_learning_tutorial.html',
    description: 'Fine-tuning pretrained models for new tasks with limited data.',
  },
  'torchvision-models': {
    id: 'torchvision-models',
    title: 'torchvision Models',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/vision/stable/models.html',
    description: 'Pretrained ResNet, VGG, EfficientNet, and other vision backbones.',
  },
  'yolo-paper': {
    id: 'yolo-paper',
    title: 'You Only Look Once: Unified Real-Time Object Detection',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1506.02640',
    description: 'Single-pass object detection treating detection as regression problem.',
  },
  'mask-rcnn-paper': {
    id: 'mask-rcnn-paper',
    title: 'Mask R-CNN',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1703.06870',
    description: 'Instance segmentation framework extending Faster R-CNN with pixel masks.',
  },
  'unet-paper': {
    id: 'unet-paper',
    title: 'U-Net: Convolutional Networks for Biomedical Image Segmentation',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1505.04597',
    description: 'Encoder-decoder architecture with skip connections for dense prediction.',
  },
  // ── NLP & Transformers ───────────────────────────────────────────────
  'stanford-cs224n': {
    id: 'stanford-cs224n',
    title: 'Stanford CS224N — NLP with Deep Learning',
    source: 'Stanford CS224N',
    type: 'course',
    url: 'http://web.stanford.edu/class/cs224n/',
    description: 'Premier NLP course covering embeddings, RNNs, transformers, and LLMs.',
  },
  'huggingface-nlp-course': {
    id: 'huggingface-nlp-course',
    title: 'Hugging Face NLP Course',
    source: 'Hugging Face',
    type: 'course',
    url: 'https://huggingface.co/learn/nlp-course/chapter1/1',
    description: 'Hands-on transformers course using the Hugging Face ecosystem.',
  },
  'word2vec-paper': {
    id: 'word2vec-paper',
    title: 'Efficient Estimation of Word Representations (Word2Vec)',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1300.4546',
    description: 'Skip-gram and CBOW models for dense word embeddings from co-occurrence.',
  },
  'glove-paper': {
    id: 'glove-paper',
    title: 'GloVe: Global Vectors for Word Representation',
    source: 'Stanford NLP',
    type: 'paper',
    url: 'https://nlp.stanford.edu/pubs/glove.pdf',
    description: 'Combines global matrix factorization with local context window methods.',
  },
  'lstm-paper': {
    id: 'lstm-paper',
    title: 'Long Short-Term Memory',
    source: 'Neural Computation',
    type: 'paper',
    url: 'https://www.bioinf.jku.at/publications/older/2604.pdf',
    description: 'Gated recurrent architecture solving vanishing gradient in long sequences.',
  },
  'attention-paper': {
    id: 'attention-paper',
    title: 'Attention Is All You Need',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1706.03762',
    description: 'Transformer architecture paper that revolutionized NLP and beyond.',
  },
  'bert-paper': {
    id: 'bert-paper',
    title: 'BERT: Pre-training of Deep Bidirectional Transformers',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1810.04805',
    description: 'Bidirectional encoder pretraining that set new benchmarks across NLP tasks.',
  },
  'gpt3-paper': {
    id: 'gpt3-paper',
    title: 'Language Models are Few-Shot Learners (GPT-3)',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/2005.14165',
    description: 'Demonstrated emergent few-shot learning at scale with autoregressive LMs.',
  },
  'jay-alammar-attention': {
    id: 'jay-alammar-attention',
    title: 'The Illustrated Transformer',
    source: 'Jay Alammar',
    type: 'documentation',
    url: 'https://jalammar.github.io/illustrated-transformer/',
    description: 'Visual step-by-step explanation of self-attention and transformer blocks.',
  },
  'transformers-docs': {
    id: 'transformers-docs',
    title: 'Hugging Face Transformers Documentation',
    source: 'Hugging Face',
    type: 'documentation',
    url: 'https://huggingface.co/docs/transformers/index',
    description: 'Library for BERT, GPT, T5, and thousands of pretrained transformer models.',
  },
  'spacy-ner': {
    id: 'spacy-ner',
    title: 'spaCy NER Documentation',
    source: 'spaCy',
    type: 'documentation',
    url: 'https://spacy.io/usage/linguistic-features#named-entities',
    description: 'Production-ready named entity recognition pipeline and custom training.',
  },
  'seq2seq-attention-paper': {
    id: 'seq2seq-attention-paper',
    title: 'Neural Machine Translation by Jointly Learning to Align and Attend',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1409.0473',
    description: 'Introduced attention mechanism for encoder-decoder sequence models.',
  },
  // ── GenAI, LLMs & MLOps ──────────────────────────────────────────────
  'openai-gpt-best-practices': {
    id: 'openai-gpt-best-practices',
    title: 'GPT Best Practices',
    source: 'OpenAI',
    type: 'documentation',
    url: 'https://platform.openai.com/docs/guides/prompt-engineering',
    description: 'Official guide to prompt engineering strategies for LLM applications.',
  },
  'anthropic-prompt-engineering': {
    id: 'anthropic-prompt-engineering',
    title: 'Prompt Engineering Overview',
    source: 'Anthropic',
    type: 'documentation',
    url: 'https://docs.anthropic.com/en/docs/build-with-claude/prompt-engineering/overview',
    description: 'Techniques for clear, effective prompts with Claude and general LLMs.',
  },
  'rag-paper': {
    id: 'rag-paper',
    title: 'Retrieval-Augmented Generation for Knowledge-Intensive NLP Tasks',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/2005.11401',
    description: 'Foundational RAG paper combining retrieval with generative models.',
  },
  'lora-paper': {
    id: 'lora-paper',
    title: 'LoRA: Low-Rank Adaptation of Large Language Models',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/2106.09685',
    description: 'Parameter-efficient fine-tuning via low-rank weight updates.',
  },
  'peft-docs': {
    id: 'peft-docs',
    title: 'Hugging Face PEFT Documentation',
    source: 'Hugging Face',
    type: 'documentation',
    url: 'https://huggingface.co/docs/peft/index',
    description: 'Parameter-efficient fine-tuning with LoRA, prefix tuning, and adapters.',
  },
  'langchain-agents': {
    id: 'langchain-agents',
    title: 'LangChain Agents Documentation',
    source: 'LangChain',
    type: 'documentation',
    url: 'https://python.langchain.com/docs/concepts/agents/',
    description: 'Building LLM agents that reason, plan, and use external tools.',
  },
  'reAct-paper': {
    id: 'reAct-paper',
    title: 'ReAct: Synergizing Reasoning and Acting in Language Models',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/2210.03629',
    description: 'Interleaved reasoning and tool-use pattern for LLM agents.',
  },
  'mlflow-docs': {
    id: 'mlflow-docs',
    title: 'MLflow Documentation',
    source: 'MLflow',
    type: 'documentation',
    url: 'https://mlflow.org/docs/latest/index.html',
    description: 'Open platform for experiment tracking, model registry, and deployment.',
  },
  'torchserve-docs': {
    id: 'torchserve-docs',
    title: 'TorchServe Documentation',
    source: 'PyTorch',
    type: 'documentation',
    url: 'https://pytorch.org/serve/',
    description: 'Production model serving for PyTorch with REST and gRPC APIs.',
  },
  'onnx-docs': {
    id: 'onnx-docs',
    title: 'ONNX Documentation',
    source: 'ONNX',
    type: 'documentation',
    url: 'https://onnx.ai/onnx/intro/',
    description: 'Open format for interoperable model serialization across frameworks.',
  },
  'docker-docs': {
    id: 'docker-docs',
    title: 'Docker Documentation',
    source: 'Docker',
    type: 'documentation',
    url: 'https://docs.docker.com/get-started/',
    description: 'Containerization fundamentals for packaging ML applications.',
  },
  'kubernetes-ml': {
    id: 'kubernetes-ml',
    title: 'Kubernetes Documentation',
    source: 'Kubernetes',
    type: 'documentation',
    url: 'https://kubernetes.io/docs/home/',
    description: 'Orchestrating containerized ML services at scale in production.',
  },
  'evidently-ai': {
    id: 'evidently-ai',
    title: 'Evidently AI — ML Monitoring',
    source: 'Evidently AI',
    type: 'documentation',
    url: 'https://docs.evidentlyai.com/',
    description: 'Open-source tools for data drift detection and model performance monitoring.',
  },
  'fairlearn-docs': {
    id: 'fairlearn-docs',
    title: 'Fairlearn Documentation',
    source: 'Fairlearn',
    type: 'documentation',
    url: 'https://fairlearn.org/main/user_guide/index.html',
    description: 'Assessing and mitigating unfairness in machine learning models.',
  },
  'model-cards-paper': {
    id: 'model-cards-paper',
    title: 'Model Cards for Model Reporting',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1810.03993',
    description: 'Framework for transparent documentation of ML model capabilities and limitations.',
  },
  'eu-ai-act': {
    id: 'eu-ai-act',
    title: 'EU Artificial Intelligence Act',
    source: 'European Union',
    type: 'documentation',
    url: 'https://artificialintelligenceact.eu/',
    description: 'Comprehensive EU regulatory framework for high-risk AI systems.',
  },
  'nist-ai-rmf': {
    id: 'nist-ai-rmf',
    title: 'NIST AI Risk Management Framework',
    source: 'NIST',
    type: 'documentation',
    url: 'https://www.nist.gov/itl/ai-risk-management-framework',
    description: 'US framework for trustworthy AI development and governance.',
  },
  'google-responsible-ai': {
    id: 'google-responsible-ai',
    title: 'Google Responsible AI Practices',
    source: 'Google',
    type: 'documentation',
    url: 'https://ai.google/responsibility/responsible-ai-practices/',
    description: 'Industry guidelines for building fair, accountable AI systems.',
  },
  'gan-paper': {
    id: 'gan-paper',
    title: 'Generative Adversarial Networks',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/1406.2661',
    description: 'Adversarial training framework for generative modeling.',
  },
  'ddpm-paper': {
    id: 'ddpm-paper',
    title: 'Denoising Diffusion Probabilistic Models',
    source: 'arXiv',
    type: 'paper',
    url: 'https://arxiv.org/abs/2006.11239',
    description: 'Foundational diffusion model paper powering modern image generation.',
  },
  'mit-6034': {
    id: 'mit-6034',
    title: 'MIT 6.034 — Artificial Intelligence',
    source: 'MIT',
    type: 'course',
    url: 'https://ocw.mit.edu/courses/6-034-artificial-intelligence-fall-2010/',
    description: 'Classic AI course covering search, knowledge, learning, and reasoning.',
  },
  'stanford-cs330': {
    id: 'stanford-cs330',
    title: 'Stanford CS330 — Deep Multi-Task and Meta Learning',
    source: 'Stanford',
    type: 'course',
    url: 'https://cs330.stanford.edu/',
    description: 'Advanced course on multi-task learning, meta-learning, and transfer.',
  },
};

/** Resolve catalog IDs to reference objects. */
const pick = (...ids) => ids.map((id) => {
  const ref = CATALOG[id];
  if (!ref) throw new Error(`Missing catalog reference: ${id}`);
  return ref;
});

/** Deduplicate references by id, sorted alphabetically. */
function dedupeById(refs) {
  const map = new Map();
  for (const ref of refs) map.set(ref.id, ref);
  return [...map.values()].sort((a, b) => a.id.localeCompare(b.id));
}

export const TRACK_REFERENCES = {
  python: pick(
    'python-tutorial-intro',
    'python-datamodel',
    'cs106a-python',
    'real-python-variables',
    'python-packaging-guide',
  ),
  data: pick(
    'numpy-quickstart',
    'pandas-getting-started',
    'matplotlib-pyplot',
    'kaggle-pandas',
    'kaggle-data-viz',
  ),
  ml: pick(
    'stanford-cs229',
    'esl-hastie',
    'coursera-andrew-ng',
    'scikit-learn-user-guide',
    'kaggle-intro-ml',
  ),
  dl: pick(
    'goodfellow-dl-book',
    'stanford-cs230',
    'stanford-cs231n',
    'fastai-course',
    'pytorch-tutorials',
  ),
  ai: pick(
    'stanford-cs224n',
    'huggingface-nlp-course',
    'attention-paper',
    'gpt3-paper',
    'fairlearn-docs',
  ),
};

export const TOPIC_REFERENCES = {
  'py-vars-types': pick('python-tutorial-intro', 'python-datamodel', 'real-python-variables', 'cs106a-python'),
  'py-operators': pick('python-operators-doc', 'real-python-operators', 'python-tutorial-intro', 'cs106a-python'),
  'py-strings': pick('python-strings-doc', 'real-python-strings', 'python-fstrings-pep498', 'python-input-output'),
  'py-io': pick('python-input-output', 'python-repl', 'python-tutorial-intro', 'cs106a-python'),
  'py-env': pick('python-venv-doc', 'pip-user-guide', 'python-packaging-guide', 'python-modules-doc'),
  'py-conditionals': pick('python-if-doc', 'python-tutorial-intro', 'cs106a-python', 'real-python-operators'),
  'py-loops': pick('python-loops-doc', 'python-comprehensions-doc', 'cs106a-python', 'real-python-variables'),
  'py-functions': pick('python-functions-doc', 'python-tutorial-intro', 'cs106a-python', 'real-python-scope'),
  'py-scope': pick('real-python-scope', 'python-lambda-doc', 'python-functions-doc', 'python-datamodel'),
  'py-comprehensions': pick('python-comprehensions-doc', 'python-iterators-doc', 'python-loops-doc', 'real-python-variables'),
  'py-lists': pick('python-lists-doc', 'python-tutorial-intro', 'clrs-algorithms', 'cs106a-python'),
  'py-dicts': pick('python-dicts-doc', 'python-sets-doc', 'python-collections-module', 'real-python-variables'),
  'py-deque': pick('python-deque-doc', 'python-collections-module', 'clrs-algorithms', 'python-lists-doc'),
  'py-sort-search': pick('python-sort-doc', 'python-bisect-doc', 'clrs-algorithms', 'python-lists-doc'),
  'py-collections': pick('python-collections-module', 'python-deque-doc', 'python-dicts-doc', 'python-datamodel'),
  'py-classes': pick('python-classes-doc', 'python-datamodel', 'cs106a-python', 'real-python-variables'),
  'py-inheritance': pick('python-inheritance-doc', 'python-classes-doc', 'python-abc-doc', 'real-python-scope'),
  'py-encapsulation': pick('python-properties-doc', 'python-classes-doc', 'python-datamodel', 'real-python-scope'),
  'py-patterns': pick('python-design-patterns', 'python-classes-doc', 'python-abc-doc', 'real-python-scope'),
  'py-protocols': pick('python-typing-protocol', 'python-abc-doc', 'python-type-hints-doc', 'python-datamodel'),
  'py-decorators': pick('python-decorators-doc', 'python-functions-doc', 'python-datamodel', 'real-python-scope'),
  'py-generators': pick('python-generators-doc', 'python-iterators-doc', 'python-comprehensions-doc', 'real-python-scope'),
  'py-context': pick('python-context-managers', 'python-contextlib-doc', 'python-modules-doc', 'real-python-scope'),
  'py-typehints': pick('python-type-hints-doc', 'python-dataclasses-doc', 'python-typing-protocol', 'python-datamodel'),
  'py-modules': pick('python-modules-doc', 'pip-user-guide', 'python-packaging-guide', 'python-venv-doc'),
  'np-arrays': pick('numpy-quickstart', 'numpy-ndarray', 'kaggle-python', 'numpy-indexing'),
  'np-indexing': pick('numpy-indexing', 'numpy-broadcasting', 'numpy-ndarray', 'numpy-quickstart'),
  'np-linalg': pick('numpy-linalg', 'mit-1806-linalg', '3blue1brown-linalg', 'numpy-quickstart'),
  'np-random': pick('numpy-random', 'khan-probability', 'numpy-quickstart', 'bishop-prml'),
  'np-perf': pick('numpy-performance', 'numpy-broadcasting', 'numpy-quickstart', 'numpy-ndarray'),
  'pd-dataframes': pick('pandas-getting-started', 'kaggle-pandas', 'numpy-quickstart', 'kaggle-python'),
  'pd-indexing': pick('pandas-indexing', 'pandas-getting-started', 'kaggle-pandas', 'numpy-indexing'),
  'pd-groupby': pick('pandas-groupby', 'pandas-getting-started', 'kaggle-pandas', 'pandas-indexing'),
  'pd-merge': pick('pandas-merge', 'pandas-getting-started', 'kaggle-pandas', 'pandas-indexing'),
  'pd-missing': pick('pandas-missing', 'pandas-timeseries', 'kaggle-intermediate-ml', 'pandas-getting-started'),
  'viz-matplotlib': pick('matplotlib-pyplot', 'matplotlib-oo', 'kaggle-data-viz', 'pandas-getting-started'),
  'viz-seaborn': pick('seaborn-tutorial', 'matplotlib-pyplot', 'kaggle-data-viz', 'pandas-getting-started'),
  'viz-plotly': pick('plotly-python', 'matplotlib-pyplot', 'kaggle-data-viz', 'pandas-getting-started'),
  'viz-design': pick('tufte-visual-display', 'kaggle-data-viz', 'seaborn-tutorial', 'matplotlib-pyplot'),
  'viz-specialized': pick('plotly-python', 'seaborn-tutorial', 'tufte-visual-display', 'matplotlib-oo'),
  'ml-linear-algebra': pick('3blue1brown-linalg', 'mit-1806-linalg', 'numpy-linalg', 'esl-hastie'),
  'ml-calculus': pick('3blue1brown-calculus', 'khan-multivariable-calc', 'cs229-optimization', 'goodfellow-dl-book'),
  'ml-probability': pick('khan-probability', 'bishop-prml', 'esl-hastie', 'stanford-cs229'),
  'ml-info-theory': pick('cover-thomas-info-theory', 'bishop-prml', 'esl-hastie', 'stanford-cs229'),
  'ml-optimization': pick('cs229-optimization', 'adam-paper', '3blue1brown-calculus', 'goodfellow-dl-book'),
  'ml-workflow': pick('scikit-learn-user-guide', 'kaggle-intro-ml', 'sklearn-pipeline', 'coursera-andrew-ng'),
  'ml-linear': pick('sklearn-linear-models', 'esl-hastie', 'stanford-cs229', 'coursera-andrew-ng'),
  'ml-trees': pick('sklearn-trees', 'esl-hastie', 'kaggle-intro-ml', 'stanford-cs229'),
  'ml-metrics': pick('sklearn-metrics', 'esl-hastie', 'kaggle-intro-ml', 'scikit-learn-user-guide'),
  'ml-cv': pick('sklearn-cross-validation', 'sklearn-pipeline', 'kaggle-intermediate-ml', 'scikit-learn-user-guide'),
  'ml-regression': pick('sklearn-linear-models', 'esl-hastie', 'bishop-prml', 'berkeley-cs189'),
  'ml-classification': pick('sklearn-linear-models', 'sklearn-svm', 'esl-hastie', 'stanford-cs229'),
  'ml-svm': pick('sklearn-svm', 'bishop-prml', 'esl-hastie', 'berkeley-cs189'),
  'ml-boosting': pick('xgboost-docs', 'lightgbm-docs', 'sklearn-ensemble', 'esl-hastie'),
  'ml-ensemble': pick('sklearn-ensemble', 'xgboost-docs', 'esl-hastie', 'stanford-cs229'),
  'ml-clustering': pick('sklearn-clustering', 'esl-hastie', 'bishop-prml', 'kaggle-intro-ml'),
  'ml-dimred': pick('sklearn-pca', 'van-der-maaten-tsne', 'esl-hastie', 'bishop-prml'),
  'ml-anomaly': pick('sklearn-anomaly', 'bishop-prml', 'esl-hastie', 'scikit-learn-user-guide'),
  'ml-association': pick('sklearn-association', 'esl-hastie', 'bishop-prml', 'kaggle-intro-ml'),
  'ml-gmm': pick('sklearn-mixture', 'bishop-prml', 'esl-hastie', 'sklearn-clustering'),
  'ml-scaling': pick('sklearn-preprocessing', 'sklearn-pipeline', 'kaggle-intermediate-ml', 'scikit-learn-user-guide'),
  'ml-feature-sel': pick('sklearn-feature-selection', 'esl-hastie', 'sklearn-preprocessing', 'stanford-cs229'),
  'ml-hyperparam': pick('sklearn-grid-search', 'sklearn-cross-validation', 'scikit-learn-user-guide', 'kaggle-intermediate-ml'),
  'ml-bias-variance': pick('ml-bias-variance-tradeoff', 'esl-hastie', 'bishop-prml', 'stanford-cs229'),
  'ml-interpret': pick('shap-docs', 'lime-paper', 'esl-hastie', 'fairlearn-docs'),
  'dl-nn-basics': pick('goodfellow-dl-book', '3blue1brown-nn', 'stanford-cs230', 'mit-6s191'),
  'dl-activations': pick('goodfellow-dl-book', '3blue1brown-nn', 'stanford-cs230', 'fastai-course'),
  'dl-loss': pick('goodfellow-dl-book', 'cover-thomas-info-theory', 'stanford-cs230', 'fastai-course'),
  'dl-backprop': pick('3blue1brown-nn', 'goodfellow-dl-book', 'stanford-cs230', 'pytorch-autograd'),
  'dl-init-reg': pick('dropout-paper', 'batch-norm-paper', 'goodfellow-dl-book', 'stanford-cs230'),
  'pt-tensors': pick('pytorch-tensors', 'pytorch-tutorials', 'numpy-quickstart', 'fastai-course'),
  'pt-autograd': pick('pytorch-autograd', '3blue1brown-nn', 'goodfellow-dl-book', 'pytorch-tutorials'),
  'pt-module': pick('pytorch-nn-module', 'pytorch-tutorials', 'fastai-course', 'goodfellow-dl-book'),
  'pt-training': pick('pytorch-dataloader', 'pytorch-tutorials', 'fastai-course', 'pytorch-nn-module'),
  'pt-gpu': pick('pytorch-cuda', 'pytorch-amp', 'pytorch-tutorials', 'fastai-course'),
  'dl-conv': pick('cs231n-conv-notes', 'stanford-cs231n', 'alexnet-paper', 'goodfellow-dl-book'),
  'dl-cnn-arch': pick('resnet-paper', 'vgg-paper', 'alexnet-paper', 'stanford-cs231n'),
  'dl-transfer': pick('pytorch-transfer-learning', 'torchvision-models', 'stanford-cs231n', 'fastai-course'),
  'dl-detection': pick('yolo-paper', 'stanford-cs231n', 'torchvision-models', 'fastai-course'),
  'dl-segmentation': pick('unet-paper', 'mask-rcnn-paper', 'stanford-cs231n', 'pytorch-tutorials'),
  'nlp-preprocess': pick('stanford-cs224n', 'huggingface-nlp-course', 'spacy-ner', 'kaggle-python'),
  'nlp-embeddings': pick('word2vec-paper', 'glove-paper', 'stanford-cs224n', 'huggingface-nlp-course'),
  'nlp-rnn': pick('lstm-paper', 'stanford-cs224n', 'goodfellow-dl-book', 'huggingface-nlp-course'),
  'nlp-seq2seq': pick('seq2seq-attention-paper', 'attention-paper', 'stanford-cs224n', 'huggingface-nlp-course'),
  'nlp-ner': pick('spacy-ner', 'stanford-cs224n', 'huggingface-nlp-course', 'transformers-docs'),
  'dl-attention': pick('attention-paper', 'jay-alammar-attention', 'stanford-cs224n', 'seq2seq-attention-paper'),
  'dl-transformer': pick('attention-paper', 'jay-alammar-attention', 'transformers-docs', 'stanford-cs224n'),
  'dl-positional': pick('attention-paper', 'jay-alammar-attention', 'transformers-docs', 'stanford-cs224n'),
  'dl-bert': pick('bert-paper', 'transformers-docs', 'huggingface-nlp-course', 'stanford-cs224n'),
  'dl-gpt': pick('gpt3-paper', 'transformers-docs', 'huggingface-nlp-course', 'attention-paper'),
  'ai-llm': pick('gpt3-paper', 'huggingface-nlp-course', 'stanford-cs224n', 'transformers-docs'),
  'ai-prompt': pick('openai-gpt-best-practices', 'anthropic-prompt-engineering', 'huggingface-nlp-course', 'gpt3-paper'),
  'ai-rag': pick('rag-paper', 'huggingface-nlp-course', 'transformers-docs', 'langchain-agents'),
  'ai-finetune': pick('lora-paper', 'peft-docs', 'huggingface-nlp-course', 'fastai-course'),
  'ai-agents': pick('reAct-paper', 'langchain-agents', 'anthropic-prompt-engineering', 'openai-gpt-best-practices'),
  'ai-serving': pick('mlflow-docs', 'torchserve-docs', 'onnx-docs', 'pytorch-tutorials'),
  'ai-docker': pick('docker-docs', 'kubernetes-ml', 'torchserve-docs', 'mlflow-docs'),
  'ai-monitoring': pick('evidently-ai', 'mlflow-docs', 'fairlearn-docs', 'model-cards-paper'),
  'ai-bias': pick('fairlearn-docs', 'model-cards-paper', 'esl-hastie', 'google-responsible-ai'),
  'ai-governance': pick('eu-ai-act', 'nist-ai-rmf', 'model-cards-paper', 'google-responsible-ai'),
};

export const ALL_REFERENCES = dedupeById([
  ...Object.values(TRACK_REFERENCES).flat(),
  ...Object.values(TOPIC_REFERENCES).flat(),
]);
